### ISSUE TITLE
[Question] 32bit mode crash error

### ISSUE THREAD

**Issue by fish3rman** [0vercl0k/wtf#100]
when i fuzzed 32bit target, wtf didn't recognize crash and cr3 always occurred.
but i tested with 64bit target(same source code), wtf could detect crash.

attached file is here : https://drive.google.com/file/d/1aki6kVs7wuDYc3zkmQ5M6WKfMrWUBxJW/view?usp=sharing

P.S. can u explain how to use SimulateReturnFrom32bitFunction() ? (in #96 )

**Comment by 0vercl0k** [comment]
Sorry I have been late to answer this but I have not forgotten about it :)
Planning to take a look this week-end!

Cheers

**Comment by y0ny0ns0n** [comment]
Hi.

I saw your attached file and I think cr3 occurred because you tried to read file data from file handle.
As you can see, snapshot of wtf is a memory dump and it can't contain 'file' or 'registry' or any other data which not existing on in-memory.

You should replace `fread` in your test code to any other wildcopy function like `memcpy` or `RtlCopyMemory`.

I'm rather curious how wtf detect crash on 64bit... Can you also share your 64bit version of `fuzzer_hook.cc` to clarify?

Also, `SimulateReturnFrom32bitFunction` is just same as 64bit version( `SimulateReturnFromFunction` ). If your function to **just return integer**'s attribute is `__cdecl`, there is no change but if it's attribute is `__stdcall`, set `SimulateReturnFrom32bitFunction`'s 2nd argment to count of function's argument count. That's all.

AND, you should eliminate `printf` call on you test code or using breakpoint handler like [this](https://github.com/0vercl0k/wtf/blob/4a9bf55/src/wtf/fuzzer_tlv_server.cc#L184). Otherwise, it will cause cr3.

**Comment by fish3rman** [comment]
the problem was `fread` as you mentioned.

and in the case of 64bit, i was mistaken for another binary. when i tested with the same source code, cr3 occured.

also thanks for the tips in `SimulateReturnFrom32bitFunction`

bless you

**Comment by 0vercl0k** [comment]
Thank you @y0ny0ns0n for taking care of this issue 🙏🏽
