### ISSUE TITLE
FPU/x87 state initialization

### ISSUE THREAD

**Issue by 0vercl0k** [0vercl0k/wtf#44]
Have a closer look at how this gets initialized in `wtf` - I've ignored this for a while but it'd be good to make sure it's correct. And also, maybe figure out the `0xInfinity` bit in `fpst` either in `wtf` or in `bdump` or both.

**Comment by richinseattle** [comment]
I found some discussion on LKML that said default value for the mxcsr mask is 0xffbf, which I've tested successfully under bxcpu fuzzing runs. A simplified table with the bit definitions is here:
https://help.totalview.io/previous_releases/2019/html/index.html#page/Reference_Guide/Intelx86MXSCRRegister.html

This value is normally readable by using fxsave to dump the fpu registers. Still need to figure out the DbgEng way.

**Comment by richinseattle** [comment]
A couple references. The mxcsr value is reset to 0x1f80 at boot and is the value I see in my kdmp from Windows 10 target. 
https://www.felixcloutier.com/x86/ldmxcsr

The mask will be hardcoded somewhere into the kernel. In Linux is is indeed 0xffbf.
https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/fpu/init.c#L117

**Comment by richinseattle** [comment]
I sent a PR to bdump to address this. Fixed in https://github.com/yrp604/bdump/commit/5a86bdc45acaf65a32aa9149ea47b717d899c85e
The default init value for the fpu comes from the Linux kernel but I've tested this patch on gdiplus image apis which require this mask to be correct, so probably safe to close the issue for now.

**Comment by 0vercl0k** [comment]
Awesome, thanks Rich!
