### ISSUE TITLE
Harness writing techniques

### ISSUE THREAD

**Issue by alimubasshira** [0vercl0k/wtf#88]
From your documentation, it is evident that the harness consists of three parts, initialize, test case insertion, and restoring. I am trying to understand the working of wtf with a sample application, but I was stuck at the harness generation, what exactly needs to be put in init function, the sample application is taking string input cmd line from the user while building, I am facing the error: Translation of GVA (address) failed. I have used the same init function as given in your example, as I feel it is generic and applicable for all cases since you have used the registers.

D:\fuzzing_WTF\application>D:\wtf-0.3.1\src\build\RelWithDebInfo\wtf.exe fuzz --backend=bochscpu --limit 10000000 --name application --target D:\fuzzing_WTF\application
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
Dialing to tcp://localhost:31337/..
Translation of GVA 0x50f094d820 failed

**Comment by 0vercl0k** [comment]
I cannot really help you with that amount of information - I'd need the code / state folder to be able to debug the issue. I understand that you also might be keen on doing that; I'd recommend looking into the closed issues and it might give you some clues as to what's going wrong.

Now, GVA translation failure happens when `wtf` is unable to do a virtual to physical address translation. This can happen if the memory doesn't exist (it's an AV, the backing memory has been paged out, etc.).

Cheers

**Comment by alimubasshira** [comment]
since I'm new to this I found it a little difficult to use.

This contains all files i have used.
https://drive.google.com/file/d/1L1bGOfYZvwrJvIaUq7Nz0wElCPtGsgPH/view?usp=sharing

Thank you

**Comment by 0vercl0k** [comment]
It is difficult to use :) I don't have the right access to be able to download the file.

Cheers

**Comment by 0vercl0k** [comment]
This issue hasn't moved forward for the past 12+ days - feel free to re-open once you are able to share anything that I can use to help you out :)

Cheers
