### ISSUE TITLE
Special Pool and Ram Size

### ISSUE THREAD

**Issue by 0xSensei** [0vercl0k/wtf#99]
Hello 0vercl0k,

i want to fuzz a windows driver over DeviceIoControl, i have a couple of questions.
- is the fuzzer capable of doing valid VirtualAlloc and ExAllocatePool allocations during fuzzing under bochscpu or whv ? because my targets are integer overflow and based on it will allocate less buffer than needed. which bring me to the other question.
- does the fuzzer work with Page heap and Special Pool ? 
- Can i raise the VM memory to more than 4GB, i tried to hack it manually and change it in ram.h but since whv dosent have instruction trace i cant know for sure if everything works as intended. running a test case under bochscpu work fine but in whv it report a crash and i want to know where it crashes exactly. is there a way to enable some debug mode ? 

thank you so much for the awesome fuzzer

**Comment by 0vercl0k** [comment]
Hey!

Here are some answers:

1/ You cannot allocate memory outside of execution. This is not supported because I'm not sure how to do that safely. You'd need to modify the page tables and somehow let the Windows kernel about this new range of memory it shouldn't allocate from so that it doesn't allocate this region as part of another allocation. I think it's feasible but I'm not quite sure what routes to take to implement something like this. If your target does the allocation while it runs it is totally fine, because it'll go through the kernel etc.

2/ I've done page heap and special pool fuzzing yes (checkout [Building a new snapshot fuzzer & fuzzing IDA](https://doar-e.github.io/blog/2021/07/15/building-a-new-snapshot-fuzzer-fuzzing-ida/))

3/ You should be able to raise the memory yes. I haven't actively tested this, but I don't really see why it wouldn't work. To debug with `WinHV` please check out the `README` as there is a way to get *some* tracing (coverage, not rip) which might be good enough to understand what's going on.

Thanks for the kind words!

Cheers

**Comment by 0xSensei** [comment]
Thank you for response, i couldnt find a mention for special pool in your blogpost but will do more testing before i come back here. quick test shows that bochscpu doesn't work with special pool because it didn't cause a crash in the intended crash point. 

you can close the issue if you want, i will reopen it if i need your help again. 

again thank you so much for the detailed reply

**Comment by 0vercl0k** [comment]
You're right! I think Secure pool is enabled in the `hevd.dmp` in the archive in the release section though :)

Cheers
